"""swift connect delete

Revision ID: 2f070c754197
Revises: 957589450942
Create Date: 2024-01-05 16:20:50.245219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f070c754197'
down_revision = '957589450942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_ibfk_1', type_='foreignkey')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('address')
        batch_op.drop_column('user_id')
        batch_op.drop_column('customer_email')

    with op.batch_alter_table('swift_connect_request', schema=None) as batch_op:
        batch_op.drop_column('amount')
        batch_op.drop_column('status')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('request_details')
        batch_op.drop_column('customer_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swift_connect_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_email', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('request_details', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('customer_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('amount', mysql.FLOAT(), nullable=False))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_email', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.create_foreign_key('customers_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
