"""Added sender_id and customer_id relationships

Revision ID: 432d5361e9e5
Revises: 2f070c754197
Create Date: 2024-01-05 16:22:56.884438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432d5361e9e5'
down_revision = '2f070c754197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=False))
        # batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=False))
        # batch_op.add_column(sa.Column('customer_email', sa.String(length=255), nullable=False))
        # batch_op.add_column(sa.Column('address', sa.Text(), nullable=False))
        # batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        print("yes")

    with op.batch_alter_table('swift_connect_request', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('request_details', sa.Text(), nullable=False))
        # batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        # batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        print("yes")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swift_connect_request', schema=None) as batch_op:
        batch_op.drop_column('amount')
        batch_op.drop_column('status')
        batch_op.drop_column('request_details')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('address')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
