"""customer update

Revision ID: 4894d3f1f65a
Revises: c2e049c61a9a
Create Date: 2024-01-05 16:03:35.894866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4894d3f1f65a'
down_revision = 'c2e049c61a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swift_connect_request', schema=None) as batch_op:
        # batch_op.drop_constraint('swift_connect_request_ibfk_1', type_='foreignkey')
        # batch_op.drop_column('sender_id')
        # batch_op.drop_column('customer_id')
        print("yes")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swift_connect_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('swift_connect_request_ibfk_1', 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###
