"""swift connect updated

Revision ID: 957589450942
Revises: 4894d3f1f65a
Create Date: 2024-01-05 16:15:43.542583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '957589450942'
down_revision = '4894d3f1f65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swift_connect_request', schema=None) as batch_op:
        batch_op.drop_column('sender_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swift_connect_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
